-- =====================================================================
-- RIBRE 配送(shipping_rows)クラウド同期 初期SQL
--
-- 背景: 配送CSV取込行(pages/app-v2.js の appvShipRows、localStorage
-- ribre_shipping_rows230)はこれまでクラウドへ一切送られておらず、端末ごとに
-- 孤立していた。別PCで取り込んだヤマト運賃明細がこの端末に無いため、その端末で
-- 突合済みの売上がいつまでも送料0のままになる事故が実データで確認されている。
-- sales/purchases（supabase_store_setup.sql）と同じ upsert 方式でクラウド同期する。
--
-- 実行方法: SupabaseダッシュボードのSQL Editorで全文貼り付けて実行してください。
-- 何度実行しても安全です（冪等: if not exists / drop policy if exists）。
-- 既存データは一切削除しません。
--
-- 重要: このSupabaseプロジェクトは売上管理以外のアプリ(SELKURA・値付けアシスト等)
-- とも共用しているため、authenticated全開放のポリシーは禁止（CLAUDE.md #13）。
-- supabase_mf_owner_rls.sql と同じ「RIBREメンバーのメール許可リスト」方式で
-- RLSを設定する。メンバーを追加するときは、下の select/insert/update 3ポリシーの
-- in (...) リストすべてに同じメールを足して、このSQLを再実行してください。
--
-- サイズ試算: 1行あたり約150バイト（bigint id + user_email/client_id/ship_type/
-- item_id/slip/company/status/row_key の短いtext列 + shipping(integer) +
-- updated_at）。生CSV行(raw)は保存しないため、現状の配送行6,237件でも
-- 約0.9MB程度に収まる見込み。
-- =====================================================================

-- 1) テーブル本体
--   client_id は pages/app-v2.js の keyOf() / pages/shipping-sync.js の svsRowKey() と
--   同じ値（"type|正規化伝票番号 or 商品ID or c+rowKeyハッシュ"）。これで
--   (user_email, client_id) の一意制約がそのままアプリ側の重複判定キーになり、
--   同じ行を何度pushしても upsert で1行に収束する。
--   raw（CSV1行まるごと）はここには保存しない。照合に使うのは
--   ship_type/item_id/slip/shipping のみで、row_key（rk）が重複判定を担保するため
--   raw を持つ必要が無く、容量も大きく減らせる（要件どおり）。
create table if not exists shipping_rows (
  id          bigint generated by default as identity primary key,
  user_email  text not null,
  client_id   text not null,
  ship_type   text,        -- yamato1（発行済データ） / yamato2（運賃明細） / sagawa
  item_id     text,
  slip        text,
  shipping    integer,
  company     text,
  status      text,        -- 未照合 / 配送CSV一致 など（appvMatchShippingが更新するstatusと同じ語彙）
  row_key     text,        -- appvShipRowHash() が作る rk（伝票番号も商品IDも無い行の重複判定用）
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

-- 2) (user_email, client_id) で一意に → upsert(on_conflict=user_email,client_id)は更新、
--    重複行は作られない（supabase_store_setup.sqlのsales/purchasesと同じ方式）
create unique index if not exists shipping_rows_user_client_unique
  on shipping_rows (user_email, client_id);

-- 3) 伝票番号での検索用インデックス
create index if not exists shipping_rows_user_slip_idx
  on shipping_rows (user_email, slip);

-- 4) updated_at 自動更新トリガ
--    set_updated_at() は supabase_store_setup.sql で既に作られている可能性が高いが、
--    このSQL単体でも実行できるように create or replace で再定義する（同一内容なので無害）。
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists shipping_rows_set_updated_at on shipping_rows;
create trigger shipping_rows_set_updated_at
  before update on shipping_rows
  for each row execute function set_updated_at();

-- 5) RLS: メンバー許可リスト方式（supabase_mf_owner_rls.sqlと同じ）。
--    anonポリシーは作らない＝未ログインからは一切アクセス不可。
--    delete ポリシーも意図的に作らない（同期は追加専用。このアプリの仕様上
--    クラウド側の行を消す操作は無い。手動で消したい場合はダッシュボードから）。
alter table shipping_rows enable row level security;

drop policy if exists shipping_rows_select_member on shipping_rows;
drop policy if exists shipping_rows_insert_member on shipping_rows;
drop policy if exists shipping_rows_update_member on shipping_rows;

-- メンバー追加時はこのリストにメールを足して再実行する
create policy shipping_rows_select_member on shipping_rows
for select to authenticated
using ((auth.jwt() ->> 'email') in ('ribre2016@gmail.com', 'k.sado@ribre.co.jp'));

create policy shipping_rows_insert_member on shipping_rows
for insert to authenticated
with check ((auth.jwt() ->> 'email') in ('ribre2016@gmail.com', 'k.sado@ribre.co.jp'));

create policy shipping_rows_update_member on shipping_rows
for update to authenticated
using ((auth.jwt() ->> 'email') in ('ribre2016@gmail.com', 'k.sado@ribre.co.jp'))
with check ((auth.jwt() ->> 'email') in ('ribre2016@gmail.com', 'k.sado@ribre.co.jp'));
