-- 税理士ワークスペース Phase 6: 事務所の管理（役割・承認ワークフロー）
-- 設計書: docs/TAX_WORKSPACE_PHASE6_PLAN.md §2 / §10.2、PHASE7_PLAN.md §14
-- 実行方法: Supabaseダッシュボード → SQL Editor で実行。何度実行しても安全（冪等）。
--
-- 方針は既存と同じ: **ポリシーを一切作らない**（service role のみ）。
-- このSupabaseプロジェクトは他アプリと共用のため、authenticated 全体へ開放しない。
--
-- ⚠ tax_workspace_settings は supabase_tax_advisor.sql で
--   **「id=1 の1行だけを持つ設定テーブル」**として既に作られている。
--   最初この形を確認せず key/value 型の別テーブルとして書いてしまい、
--   `column "skey" ... does not exist` で失敗した（2026-08-04）。
--   既存の形に合わせて**列を1つ足す**のが正しい。

-- =========================================
-- 1. 税理士に役割を持たせる（admin / staff）
-- =========================================
-- admin … 事務所の管理者（所長）。承認・全員の操作履歴の閲覧ができる
-- staff … 担当者。既定はこちら
alter table tax_advisors add column if not exists role text not null default 'staff';

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'tax_advisors_role_check') then
    alter table tax_advisors
      add constraint tax_advisors_role_check check (role in ('admin', 'staff'));
  end if;
end $$;

-- =========================================
-- 2. 承認するかどうかの設定（既存の設定テーブルに列を足す）
-- =========================================
-- 'none'     … 承認しない（既定。小規模事務所に承認の手間を強制しない）
-- 'required' … 担当者の登録は承認待ちに積み、管理者が承認して初めてMFへ送る
alter table tax_workspace_settings
  add column if not exists approval_policy text not null default 'none';

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'tax_workspace_settings_approval_valid') then
    alter table tax_workspace_settings
      add constraint tax_workspace_settings_approval_valid
      check (approval_policy in ('none', 'required'));
  end if;
end $$;

-- 1行だけのテーブルなので、無ければ作る（既にあれば何もしない）
insert into tax_workspace_settings (id, closed_term_policy)
values (1, 'warn')
on conflict (id) do nothing;

-- =========================================
-- 3. 承認待ちの登録依頼
-- =========================================
-- approval_policy='required' のとき、staff の「登録」は MF へ送らずここへ積む。
-- admin が承認したときに初めて MF へ送る。
--
-- ⚠ payload には journalize へ渡す内容をそのまま入れる。
--   snapshot は依頼した時点の明細（日付・金額・摘要）。承認の実行時に
--   今の明細と突き合わせ、変わっていたら実行しない（設計書§10.2-1）。
create table if not exists tax_journal_requests (
  id             bigint generated by default as identity primary key,
  requested_by   text not null,                     -- 依頼した担当者のメール
  transaction_id text not null,
  payload        jsonb not null,                    -- journalize へ渡す内容そのまま
  snapshot       jsonb,                             -- 依頼時点の明細
  status         text not null default 'pending',   -- pending / approved / rejected
  decided_by     text,
  decided_reason text,
  decided_at     timestamptz,
  journal_id     text,                              -- 承認して作成できた仕訳
  created_at     timestamptz not null default now()
);

create index if not exists tax_journal_requests_status_idx
  on tax_journal_requests (status, created_at desc);
create index if not exists tax_journal_requests_requester_idx
  on tax_journal_requests (requested_by);
-- 同じ明細に対する「承認待ち」は1件だけにする（二重依頼を防ぐ）
create unique index if not exists tax_journal_requests_pending_unique
  on tax_journal_requests (transaction_id) where status = 'pending';

alter table tax_journal_requests enable row level security;
-- ポリシーは作らない（service role のみ）

-- =========================================
-- 4. 実行後に決めること（どちらも任意・後からでよい）
-- =========================================
-- (a) 誰を管理者にするか。**管理者は承認を経ずに登録できる**ので最小人数に絞ること。
--     update tax_advisors set role = 'admin' where lower(email) = lower('所長のメール');
--
-- (b) 承認を必須にするか。既定は 'none'（承認しない）。
--     update tax_workspace_settings set approval_policy = 'required' where id = 1;
--     戻すとき: update tax_workspace_settings set approval_policy = 'none' where id = 1;
--
-- ⚠ この2つはSQLで直接変えるため、**アプリの操作履歴には残りません**。
--   変更したら「いつ・誰が・何を」を事務所側で書き残す運用にしてください（所長レビューの指摘）。
--
-- 確認用:
--   select email, name, role, enabled from tax_advisors order by role, email;
--   select id, closed_term_policy, approval_policy from tax_workspace_settings;
