-- 税理士ワークスペース Phase 1: 許可リストと操作履歴
-- 設計書: docs/TAX_WORKSPACE_PLAN.md
-- 実行方法: Supabaseダッシュボード → SQL Editor で実行。何度実行しても安全（冪等）。
--
-- 方針:
--   どちらのテーブルも **ポリシーを一切作らない**。
--   Vercel Serverless Functions が SUPABASE_SERVICE_ROLE_KEY（RLSを素通りする
--   service role）でのみ読み書きするため、authenticated/anon から直接触れる必要が無い。
--   このSupabaseプロジェクトは他アプリ（SELKURA等）と共用のため、
--   authenticated 全体へ開放すると別アプリのログインユーザーにも見えてしまう。
--   mf_tokens と同じ考え方（supabase_mf_evidence.sql 参照）。

-- =====================
-- 1. 税理士の許可リスト
-- =====================
-- ここに載っているメールでログインした人だけが税理士ワークスペースを使える。
-- 行を消す（または enabled=false）と即座に権限が切れる。
create table if not exists tax_advisors (
  id         bigint generated by default as identity primary key,
  email      text not null,
  name       text,
  enabled    boolean not null default true,
  note       text,
  created_at timestamptz not null default now()
);

create unique index if not exists tax_advisors_email_unique on tax_advisors (lower(email));

alter table tax_advisors enable row level security;
-- ポリシーは作らない（service role のみ）
drop policy if exists tax_advisors_select_auth on tax_advisors;
drop policy if exists tax_advisors_all_auth on tax_advisors;

-- =====================
-- 2. 操作履歴（追記専用）
-- =====================
-- MF側では仕訳が全て「連携アプリ」名義で作られ、誰が作ったか分からない。
-- そのため **このテーブルがこの機能の唯一の監査証跡** になる。
-- 更新・削除のポリシーを作らないことで追記専用にする。
create table if not exists tax_advisor_actions (
  id             bigint generated by default as identity primary key,
  actor_email    text not null,        -- 操作した税理士
  action         text not null,        -- 'journalize' / 'attach_voucher' など
  transaction_id text,                 -- 対象の明細ID
  journal_id     text,                 -- 作成された仕訳ID
  account_id     text,
  tax_id         text,
  evidence_ids   text[],               -- 添付した証憑
  result         text not null,        -- 'ok' / 'journal_ok_voucher_failed' / 'failed'
  error_message  text,
  payload        jsonb,                -- 送信内容そのまま（後から検証できるように）
  created_at     timestamptz not null default now()
);

create index if not exists tax_advisor_actions_created_idx on tax_advisor_actions (created_at desc);
create index if not exists tax_advisor_actions_actor_idx on tax_advisor_actions (actor_email);

alter table tax_advisor_actions enable row level security;
-- ポリシーは作らない（service role のみ・追記専用）
drop policy if exists tax_advisor_actions_select_auth on tax_advisor_actions;
drop policy if exists tax_advisor_actions_insert_auth on tax_advisor_actions;

-- =====================
-- 3. 税理士を登録する（メールを実際のものに置き換えて実行）
-- =====================
-- insert into tax_advisors (email, name, note)
-- values ('zeirishi@example.com', '〇〇税理士事務所', '2026-08 追加')
-- on conflict (lower(email)) do update set enabled = true;

-- 確認用
-- select id, email, name, enabled, created_at from tax_advisors order by id;
-- select * from tax_advisor_actions order by created_at desc limit 50;
