-- =====================================================================
-- RIBRE Ver61.0  Supabaseを「データの正」にするための初期SQL
-- Supabase ダッシュボード → SQL Editor で、上から順に1回だけ実行してください。
-- 何度実行しても安全（IF NOT EXISTS / ON CONFLICT 済み）です。
-- （本番Supabaseには適用済み。新環境構築や再現用に残置）
-- =====================================================================

-- 1) 端末をまたいで行を一意に上書き(upsert)するためのキー列を追加
alter table sales     add column if not exists client_id  text;
alter table purchases add column if not exists client_id  text;

-- created_at / updated_at が無い場合に備えて追加
alter table sales     add column if not exists created_at timestamptz default now();
alter table sales     add column if not exists updated_at timestamptz default now();
alter table purchases add column if not exists created_at timestamptz default now();
alter table purchases add column if not exists updated_at timestamptz default now();

-- 2) 既存データに client_id を付与（まだ空のものだけ。既存データは消えません）
update sales     set client_id = 'db_' || id::text where client_id is null or client_id = '';
update purchases set client_id = 'db_' || id::text where client_id is null or client_id = '';

-- 3) (user_email, client_id) で一意に → 再保存は更新、重複は作られない
create unique index if not exists sales_user_client_unique
  on sales (user_email, client_id);
create unique index if not exists purchases_user_client_unique
  on purchases (user_email, client_id);

-- 4) updated_at 自動更新トリガ
create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists sales_set_updated_at on sales;
create trigger sales_set_updated_at
  before update on sales
  for each row execute function set_updated_at();

drop trigger if exists purchases_set_updated_at on purchases;
create trigger purchases_set_updated_at
  before update on purchases
  for each row execute function set_updated_at();

-- =====================================================================
-- 5) 画面設定をクラウド共有するためのテーブル（任意・あると望ましい）
--    ※ Supabase接続設定・ログイン情報・APIキーはここには保存しません（端末保存のまま）
-- =====================================================================
create table if not exists app_settings (
  id          bigint generated by default as identity primary key,
  user_email  text not null,
  skey        text not null,
  value       jsonb,
  updated_at  timestamptz default now()
);

create unique index if not exists app_settings_user_key_unique
  on app_settings (user_email, skey);

alter table app_settings enable row level security;

drop policy if exists app_settings_select_own on app_settings;
drop policy if exists app_settings_insert_own on app_settings;
drop policy if exists app_settings_update_own on app_settings;
drop policy if exists app_settings_delete_own on app_settings;

create policy app_settings_select_own on app_settings
  for select using (user_email = auth.jwt() ->> 'email');
create policy app_settings_insert_own on app_settings
  for insert with check (user_email = auth.jwt() ->> 'email');
create policy app_settings_update_own on app_settings
  for update using (user_email = auth.jwt() ->> 'email')
              with check (user_email = auth.jwt() ->> 'email');
create policy app_settings_delete_own on app_settings
  for delete using (user_email = auth.jwt() ->> 'email');

drop trigger if exists app_settings_set_updated_at on app_settings;
create trigger app_settings_set_updated_at
  before update on app_settings
  for each row execute function set_updated_at();
