-- 税理士ワークスペース Phase 6: 事務所の管理（役割・承認ワークフロー）
-- 設計書: docs/TAX_WORKSPACE_PHASE6_PLAN.md §2 / §10.2、PHASE7_PLAN.md §14
-- 実行方法: Supabaseダッシュボード → SQL Editor で実行。何度実行しても安全（冪等）。
--
-- 方針は既存と同じ: **ポリシーを一切作らない**（service role のみ）。
-- このSupabaseプロジェクトは他アプリと共用のため、authenticated 全体へ開放しない。

-- =========================================
-- 1. 税理士に役割を持たせる（admin / staff）
-- =========================================
-- admin … 事務所の管理者（所長）。承認・職員の無効化・全員の操作履歴の閲覧ができる
-- staff … 担当者。既定はこちら
alter table tax_advisors add column if not exists role text not null default 'staff';

-- 想定外の値が入らないようにする（既存行は 'staff' で埋まる）
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'tax_advisors_role_check'
  ) then
    alter table tax_advisors
      add constraint tax_advisors_role_check check (role in ('admin', 'staff'));
  end if;
end $$;

-- =========================================
-- 2. 事務所ごとの設定（承認するかどうか等）
-- =========================================
-- 1行だけ使う（key で引く）。決算済み期の扱いは既存の app_settings 側にあるため、
-- ここは事務所の運用に関わる設定だけを持つ。
create table if not exists tax_workspace_settings (
  skey       text primary key,
  value      jsonb not null,
  updated_by text,
  updated_at timestamptz not null default now()
);

alter table tax_workspace_settings enable row level security;
-- ポリシーは作らない（service role のみ）

-- 既定は 'none'（承認しない）。小規模事務所に承認の手間を強制しないため。
insert into tax_workspace_settings (skey, value, updated_by)
values ('approval_policy', '"none"'::jsonb, 'system')
on conflict (skey) do nothing;

-- =========================================
-- 3. 承認待ちの登録依頼
-- =========================================
-- approval_policy='required' のとき、staff の「登録」は MF へ送らずここへ積む。
-- admin が承認したときに初めて MF へ送る。
--
-- ⚠ payload には journalize へ渡す内容をそのまま入れる。
--   承認の実行時に、依頼した時点の明細（金額・日付・摘要）と
--   今の明細を突き合わせ、変わっていたら実行しない（設計書§10.2-1）。
create table if not exists tax_journal_requests (
  id             bigint generated by default as identity primary key,
  requested_by   text not null,                     -- 依頼した担当者のメール
  transaction_id text not null,
  payload        jsonb not null,                    -- journalize へ渡す内容そのまま
  snapshot       jsonb,                             -- 依頼時点の明細（日付・金額・摘要）
  status         text not null default 'pending',   -- pending / approved / rejected
  decided_by     text,
  decided_reason text,
  decided_at     timestamptz,
  journal_id     text,                              -- 承認して作成できた仕訳
  created_at     timestamptz not null default now()
);

create index if not exists tax_journal_requests_status_idx
  on tax_journal_requests (status, created_at desc);
create index if not exists tax_journal_requests_requester_idx
  on tax_journal_requests (requested_by);
-- 同じ明細に対する「承認待ち」は1件だけにする（二重依頼を防ぐ）
create unique index if not exists tax_journal_requests_pending_unique
  on tax_journal_requests (transaction_id) where status = 'pending';

alter table tax_journal_requests enable row level security;
-- ポリシーは作らない（service role のみ）

-- =========================================
-- 4. 最初の管理者を決める
-- =========================================
-- ⚠ 実行後、**所長にあたる税理士のメールを1件だけ admin にしてください。**
--   admin は承認をスキップして直接登録できるため、人数を絞ること（設計書§11.7-5）。
--
--   update tax_advisors set role = 'admin' where lower(email) = lower('所長のメール');
--
-- 現在の状態を確認する:
--   select email, name, role, enabled from tax_advisors order by role, email;
